### ISSUE TITLE
建议提供一个能构建web预览模块（非构建临时中间文件）的方法 

### ISSUE THREAD

**Issue by wibetter** [hapjs-platform/hap-toolkit#1]
详细见：https://github.com/quickappcn/issues/issues/147

**Comment by yaotaiyang** [comment]
你是想要将快应用直接编译成h5使用吗？

**Comment by wibetter** [comment]
是的，

**Comment by wibetter** [comment]
是的，这样快应用版的组件可以同步构建一份H5版的组件，可以放到任何平台中预览和使用（可以同时预览和使用多个组件）。
